CREATE TABLE IF NOT EXISTS voluntario (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11),
    rg VARCHAR(20),
    orgao_rg VARCHAR(10),
    idade INT CHECK (idade >= 0),
    profissao VARCHAR(50),
    telefone1 VARCHAR(15) NOT NULL,
    telefone2 VARCHAR(15),
    email VARCHAR(100) UNIQUE,
    instagram VARCHAR(50),
    frequencia VARCHAR(15) NOT NULL CHECK (frequencia IN ('DIARIA', 'SEMANAL', 'QUINZENAL', 'MENSAL', 'EVENTUAL')),
    logradouro VARCHAR(100) NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    num_endereco VARCHAR(10) NOT NULL,
    complemento VARCHAR(50),
    responsavel_id INT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_voluntario_responsavel FOREIGN KEY (responsavel_id) REFERENCES responsavel(id)
);
